# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
development: true
url: "" # the base hostname & protocol for your site
baseurl: ""
title: Glixer
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: ""
github_username:  ""

# Build settings
markdown: kramdown
layouts_dir: ./_layouts
source: ./_src
destination: ./.site
plugins_dir: ./_plugins
data_dir: ./_data
includes_dir: ./_includes


gems: [jekyll-paginate, jekyll-feed, jekyll-readme-index]
permalink: pretty
paginate: 5
exclude: ["Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json"]
keep_files: ["css",
             "fonts",
             "js"]
defaults:
 -
   values:
     layout: front
